language: php
php:
  - '5.6'

before_install:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]]; then composer require --dev --no-update phpunit/phpunit 5.7.20; fi

script: phpunit --coverage-text --bootstrap=bootstrap.php tests/*Test.php
